name: stalker
description: "An android application to view and optionally modify the save files of Shadow Fight 2 game"
publish_to: 'none'

version: 1.1.2

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  change_app_package_name: ^1.5.0
  fluttertoast: ^8.2.12
  xml: ^6.5.0
  path_provider: ^2.1.5
  signals: ^6.0.2
  http: ^1.4.0
  shared_preferences: ^2.5.3
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.1
  device_info_plus: ^11.3.0
  dynamic_color: ^1.7.0
  share_plus: ^11.0.0
  file_picker: ^10.1.9
  toml: ^0.16.0
  uuid: ^4.5.1
  logger: ^2.5.0
  crypto: ^3.0.6
  pub_semver: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/sword.png
    - assets/images/house.png
    - assets/images/file.png
    - assets/images/wrench.png
    - assets/images/bug.png
    - assets/images/coin.png
    - assets/images/ruby.png
    - assets/images/forge_green.png
    - assets/images/forge_red.png
    - assets/images/forge_purple.png
    - assets/images/dojo.png
    - assets/images/lighting.png
    - assets/images/anvil.png
    - assets/images/katana.png
    - assets/images/shuriken.png
    - assets/images/amulet.png
    - assets/images/armor.png
    - assets/images/helm.png
    - assets/images/robot-assistant.png
    - assets/binaries/setup_service_arm64
    - assets/binaries/setup_service_arm
    - assets/binaries/setup_service_x86_64
    - assets/binaries/setup_service_x86
    - assets/xml/defaultRecord.xml
    - assets/enchantments/simple.toml
    - assets/enchantments/medium.toml
    - assets/enchantments/mythical.toml
    - assets/item_database.toml